
apiVersion: v1
kind: Service
metadata:
  name: cloc-api-service
spec:
  selector:
    app: cloc-api
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloc-api
spec:
  selector:
    matchLabels:
      app: cloc-api
  replicas: 4
  template:
    metadata:
      labels:
        app: cloc-api
    spec:
      containers:
      - name: cloc-api
        image: bgreenb11/cloc-api:arm
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

