apiVersion: v1
kind: Service
metadata:
  name: cloc-api-service
  namespace: gloc
spec:
  selector:
    app: cloc-api
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloc-api
  namespace: gloc
spec:
  selector:
    matchLabels:
      app: cloc-api
  replicas: 3
  template:
    metadata:
      labels:
        app: cloc-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cloc-api
          image: bgreenb11/flask-cloc-api:redis
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 5000
          imagePullPolicy: Always

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gloc
  namespace: gloc
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: cloudflare
spec:
  tls:
    - hosts:
        - gloc.homelab.benlg.dev
      secretName: gloc-tls
  rules:
    - host: gloc.homelab.benlg.dev
      http:
        paths:
          - backend:
              service:
                name: cloc-api-service
                port:
                  name: http
            path: /
            pathType: Prefix
