apiVersion: v1
kind: Service
metadata:
  name: gloc-ui-service
  namespace: gloc-ui
spec:
  selector:
    app: gloc-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gloc-ui
  namespace: gloc-ui
spec:
  selector:
    matchLabels:
      app: gloc-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: gloc-ui
    spec:
      containers:
        - name: gloc-ui
          image: bgreenb11/gloc-ui:arm
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
          imagePullPolicy: Always

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gloc-ui
  namespace: gloc-ui
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: cloudflare
spec:
  tls:
    - hosts:
        - gloc.homelab.benlg.dev
      secretName: gloc-ui-tls
  rules:
    - host: gloc.homelab.benlg.dev
      http:
        paths:
          - backend:
              service:
                name: gloc-ui-service
                port:
                  name: http
            path: /
            pathType: Prefix
