# This is a basic workflow to help you get started with Actions

name: API Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Connect Tailscale
        uses: tailscale/github-action@v1
          with:
            authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Ping CLOC API Endpoint
        run: |
          echo "::set-output name=RESPONSE::$(curl -Is http://gloc.homelab.benlg.dev/gloc?giturl=https://github.com/attendio/attendio.git | grep HTTP | cut -d ' ' -f2)"
        id: endpoint_check
      - name: Verify Endpoint Check
        if: steps.endpoint_check.RESPONSE != 200
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('CLOC API endpoint did not pass liveliness probe!')
          
        

