# This is a basic workflow to help you get started with Actions

name: API Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.22.2
      - name: OWASP ZAP Baseline Scan
        # You may pin to the exact commit or the version.
        # uses: zaproxy/action-baseline@df1ee70ea1ebbdaa1b48e6fc861e0dc0a71fedd8
        uses: zaproxy/action-baseline@v0.6.1
        with:
          # Target URL
          target: https://gloc.homelab.benlg.dev
          # The action will file the report to the GitHub issue using the issue_title input
          allow_issue_writing: false


        
      

        

